version: "3.8"

services:
  edge:
    build: ./edge
    container_name: edge-service
    depends_on:
      - cloud
    restart: always

  cloud:
    build: ./cloud
    container_name: cloud-api
    ports:
      - "5000:5000"
    restart: always
